### ISSUE TITLE
Adds new lines at the bottom of saved file

### ISSUE THREAD

**Issue by shanemcgraw** [pbhogan/whitespacer#1]
It seems that this package, upon autosave, will append at least one line to the bottom of any file it trims.

**Comment by pbhogan** [comment]
The default value for ensureTrailingNewlines is 2 and if you set it to 0 either as a global package setting or per scope, it will append no lines. I did find a bug that setting it to 0 will not actually trim empty lines, which should be fixed shortly.

That said, you probably want to use Atom's builtin whitespace package instead of this. This fork basically exists to cater for some of my personal preferences that the builtin package does not handle (add multiple lines to end of file on save and conversion of two spaces to tabs).
